name: Pull Request Text Generator Workflow

on:
  pull_request:
    types: [opened, edited, reopened]  

jobs:
    generate-pr-text-on-opened-pr:
      runs-on: ubuntu-latest
      steps:
        - name: Run Auto PR on initial open PR
          if: github.event_name == 'pull_request'
          id: auto_pr_for_pr
          uses: vblagoje/auto-pr@main
          with:
            openai_api_key: ${{ secrets.OPENAI_API_KEY }}
            user_prompt: ${{ github.event.pull_request.body }}

        - name: Update PR description
          uses: vblagoje/update-pr@main
          with:
            pr-body: ${{ steps.auto_pr_for_pr.outputs.pr-text }} 